name: Build

on:
  push:
    branches:
     - master
  pull_request:

permissions: write-all

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    container:
      image: 'devkitpro/devkita64'

    steps:
      - uses: actions/checkout@v2

      - name: build
        run: make -j2

      - name: test
        run: ls -la
        
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          prerelease: false
          draft: false
          body: ${{ github.event.head_commit.message }}
          files: vibration-tester-for-Nintendo-Switch.nro
          name: "Switch Release #${{ github.run_number }}"